CR-7012 Step for report PR
codefresh-io/argo-hub pull request #12
Opened 2021-12-13 12:49 UTC by vadim-kharin-codefresh

2021-12-13 15:25 UTC, pasha-codefresh commented on workflows/image-enricher/versions/0.0.1/docs/image-enricher.md
> +# send-message
wrong header

2021-12-13 15:25 UTC, pasha-codefresh commented on workflows/image-enricher/versions/0.0.1/docs/image-enricher.md
> +Enrich codefresh image with PRs and Issues info
i would add details how and where it will be consumed

2021-12-13 15:26 UTC, pasha-codefresh commented on workflows/image-enricher/versions/0.0.1/docs/image-enricher.md
> +* GIT_PROVIDER_NAME (optional) - name of git provider to use from Codefresh integrations screen
it is not supported for v2

2021-12-13 15:26 UTC, pasha-codefresh commented on workflows/image-enricher/versions/0.0.1/docs/image-enricher.md
> +no outputs
i think it is do have an output

2021-12-13 15:26 UTC, pasha-codefresh commented on workflows/image-enricher/versions/0.0.1/workflowTemplate.yaml
> +  name: argo-hub.image-enricher.0.0.1
rename

2021-12-13 15:27 UTC, pasha-codefresh commented on workflows/image-enricher/versions/0.0.1/workflowTemplate.yaml
> +    argo-hub/description: 'Enrich codefresh image with PRs and Issues info'
change

2021-12-13 15:27 UTC, pasha-codefresh requested changes
added comments

2021-12-13 18:36 UTC, itai-codefresh commented
hey there thanks for the contribution :)

few comments:

1. you have missing the source code for building you image
2. the image name is not according to the rqeuired pattern
3. we need to create the new image in quay, for now it needs to be done by codefresh team till we get it automatically added
4. i suggest we create a workflowTemplate for codefresh CSDP in which you will have this image enricher template so that we have everything grouped correctly
5. lets use codefresh icon

well done :)

2021-12-14 13:41 UTC, itai-codefresh approved these changes

2021-12-14 13:42 UTC, merged