Workflow temp1 (#380)
codefresh-io/argo-hub pull request #381
Opened 2022-07-20 17:37 UTC by matthewchungcodefresh

* Adding kaniko-add-template

* revert changes

* Update

* Update

* Fix indentation

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Rename template to jira

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* change rbac name

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* repository update

* fix spelling error in command

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* remove file

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Update output variables

* Update output

* Update Dockerfile

* Update

* Update workflowTemplate.yaml

* fixing vulnerabilities

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* using alpine image instead

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Fix template name

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* update templates

* Update workflowTemplate.yaml

* changes from classic to CSDP

* Update workflowTemplate.yaml

* Jira complete

* Update workflowTemplate.yaml

* Pull request for jira integration template (#329)

* Adding kaniko-add-template

* revert changes

* Update

* Update

* Fix indentation

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Rename template to jira

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* change rbac name

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* repository update

* fix spelling error in command

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* remove file

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Update output variables

* Update output

* Update Dockerfile

* Update

* Update workflowTemplate.yaml

* fixing vulnerabilities

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* using alpine image instead

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Fix template name

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* update templates

* Update workflowTemplate.yaml

* changes from classic to CSDP

* Update workflowTemplate.yaml

* Jira complete

* Update workflowTemplate.yaml

Co-authored-by: Laurent <laurent.rochette@codefresh.io>

* Initial commit

* Update sonar-scanner.md

* Version 1.0.0 complete

* Added/Modified workflows/jira/sonar.sensor.yaml, workflows/jira/cdp-csdp-matthew-hub.ingress.yaml, workflows/jira/sonar.event-source.yaml, workflows/jira/sonar-test.workflow-template.yaml

* update

* add command

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* add command

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Added/Modified workflows/sonar.sensor.yaml, workflows/cdp-csdp-matthew-hub.ingress.yaml, workflows/sonar.event-source.yaml, workflows/sonar-test.workflow-template.yaml

* remvoe test template

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* remvoe test template

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* rename template

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* test on Tue Jun 21 17:16:08 MDT 2022

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* test on Tue Jun 21 17:17:55 MDT 2022

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Added/Modified workflows/testing.sensor.yaml, workflows/cdp-csdp-matthew-hub.ingress.yaml, workflows/testing.event-source.yaml, workflows/argo-hub.ci-simple.0.0.1.workflow-template.yaml

* Added/Modified workflows/testing-2.sensor.yaml, workflows/cdp-csdp-matthew-hub.ingress.yaml, workflows/testing-2.event-source.yaml

* Sonar Update

* svg changes

* remove test files

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Fix stuff

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Update Dockerfile

* Jira fixed readme links

* Update workflowTemplate.yaml

* datree update

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Sonar update

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* Update workflowTemplate.yaml

* V0.0.1 commit

* Delete workflows/aqua directory

* Delete workflows/registry directory

* delete files

* Sonar template for CSDP (#367)

* Adding kaniko-add-template

* revert changes

* Update

* Update

* Fix indentation

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Rename template to jira

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* change rbac name

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* repository update

* fix spelling error in command

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* remove file

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Update output variables

* Update output

* Update Dockerfile

* Update

* Update workflowTemplate.yaml

* fixing vulnerabilities

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* using alpine image instead

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Fix template name

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* update templates

* Update workflowTemplate.yaml

* changes from classic to CSDP

* Update workflowTemplate.yaml

* Jira complete

* Update workflowTemplate.yaml

* Pull request for jira integration template (#329)

* Adding kaniko-add-template

* revert changes

* Update

* Update

* Fix indentation

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Rename template to jira

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* change rbac name

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* repository update

* fix spelling error in command

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* remove file

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Update output variables

* Update output

* Update Dockerfile

* Update

* Update workflowTemplate.yaml

* fixing vulnerabilities

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* using alpine image instead

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* Fix template name

Signed-off-by: Laurent <laurent.rochette@codefresh.io>

* update templates

* Update workflowTemplate.yaml

* changes from classic to CSDP

* Update workflowTemplate.yaml

* Jira complete

* Update workflowTemplate.yaml

Co-authored-by: Laurent <laurent.rochette@codefresh.io>

* Initial commit

* Update sonar-scanner.md

* Version 1.0.0 complete

* Added/Modified workflows/jira/sonar.sensor.yaml, workflows/jira/cdp-csdp-matthew-hub.ingress.yaml, workflows/jira/sonar.event-source.yaml, workflows/jira/sonar-test.workflow-template.yaml

* update

* add command

Signed-off-by: Laurent <laurent [...]

2022-07-21 20:59 UTC, lrochette requested changes
the first paragraph to the CHANGELOG needs to be changed. It's a little confusing

2022-07-21 21:09 UTC, lrochette reviewed
There are way too many parameters.
Can you imagine what will need to be done for something trying to create a CI using the pipeline wizard?
Try to reduce the number of parameters to 10 or by making assumptions.
For example 
* For Jira authentication, simply use 1 secret and make assumption on the key used (token, username, .....) and hardcode them on the call where needed
* same for Sonar
* Hardcode the ISSUE project and customfields (so there is an example). I don't expect those to be picked in a real scenario from the webhook payload but either be hardcoded to calculated during the run
* the image SHA should be grabbed from the build (it's not something you know at the start of the workflow)
* ....

Make sense?

2022-07-28 07:52 UTC, eti-codefresh requested changes

2022-07-28 07:52 UTC, eti-codefresh commented on workflows/jira-scan-workflow/versions/0.0.1/README.md
> +[Full rbac permissions list](./rbac.yaml)
please give full path

2022-07-28 07:52 UTC, eti-codefresh commented on workflows/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +    argo-hub/icon-background: "#f4f4f4"
argo-hub/icon_background: "#f4f4f4"

2022-07-28 07:52 UTC, eti-codefresh commented on workflows/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +    - name: rollout-10
need to add 
      metadata:
        annotations:

2022-07-28 07:52 UTC, eti-codefresh commented on workflows/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +    - name: rollout-33
need to add
metadata:
annotations:

2022-07-28 07:52 UTC, eti-codefresh commented on workflows/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +    # canary rollout template 100%
need to add
metadata:
annotations:

2022-07-29 20:36 UTC, lrochette commented
@eti-codefresh was this template not supposed to go in the examples folder?
This is not a plugin!

2022-07-29 21:36 UTC, closed without merging