Workflowtemp2 (#397)
codefresh-io/argo-hub pull request #398
Opened 2022-07-29 22:01 UTC by matthewchungcodefresh

* Add files via upload

* Update README.md

2022-07-29 22:52 UTC, lrochette requested changes

2022-07-29 22:52 UTC, lrochette commented on examples/image-test-workflow/versions/0.0.1/README.md
> +1. [image-test-template](https://github.com/codefresh-io/argo-hub/blob/main/workflows/image-test-template/versions/0.0.1/docs/image-test-template.md)
path needs to be changed, it now examples not workflows

2022-07-29 22:52 UTC, lrochette commented on examples/image-test-workflow/versions/0.0.1/README.md
> +[Full rbac permissions list](https://github.com/codefresh-io/argo-hub/blob/main/workflows/image-test-template/versions/0.0.1/rbac.yaml)
path needs to be changed, it now examples not workflows

2022-07-29 22:52 UTC, lrochette commented on examples/image-test-workflow/versions/0.0.1/docs/image-test-template.md
> +### Inputs
the lis of parameters does not match the list from workflowTemplate.yaml

2022-07-29 22:52 UTC, lrochette commented on examples/image-test-workflow/versions/0.0.1/docs/image-test-template.md
> +### Inputs
I think this list is  more accurate than the template one to be honest

2022-07-29 22:52 UTC, lrochette commented on examples/image-test-workflow/versions/0.0.1/docs/image-test-template.md
> +        root-password: echo -n 'mysql root password' | base64
if we create a secret with all the data, why do we need to pass individual values to the main template

          - name: MYSQL_SECRET
            default: mysql-secret
          - name: MYSQL_ROOT_PASSWORD
            default: root-password
          - name: MYSQL_USER
            default: user
          - name: MYSQL_PASSWORD
            default: password

only the first one is requried

2022-07-29 22:52 UTC, lrochette commented on examples/image-test-workflow/versions/0.0.1/workflowTemplate.yaml
> +          - name: MYSQL_ROOT_PASSWORD
those are not required at the top template as they are values from the secret

2022-07-29 22:52 UTC, lrochette commented on examples/image-test-workflow/versions/0.0.1/workflowTemplate.yaml
> +          - name: REPO_URL
Add default value of codefreshdemo/cf-example-unit-tests-with-composition

2022-07-29 22:52 UTC, lrochette commented on examples/image-test-workflow/versions/0.0.1/workflowTemplate.yaml
> +            default: main
default branch is master for the repo above

2022-07-29 22:52 UTC, lrochette commented on examples/image-test-workflow/versions/0.0.1/workflowTemplate.yaml
> +          - name: MYSQL_ROOT_PASSWORD
I see.
those are the keys to extract value  from the secret
just keep them hardcoded at line 147, 152 and 157 to limit the numbers of parameters

2022-07-29 23:02 UTC, lrochette requested changes
when I try to run it I get error:
templates.build inputs.parameters.REPO was not supplied 

EDIT: strange I cannot find reference to that code

2022-08-03 22:08 UTC, eti-codefresh requested changes

2022-08-03 22:08 UTC, eti-codefresh commented on examples/image-test-workflow/versions/0.0.1/workflowTemplate.yaml
> +    argo-hub/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/image-test-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/image-test-workflow/assets/icon.svg"

2022-08-03 22:08 UTC, eti-codefresh commented on examples/image-test-workflow/versions/0.0.1/workflowTemplate.yaml
> +          argo-hub-template/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/image-test-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/image-test-workflow/assets/icon.svg"

2022-08-03 22:08 UTC, eti-codefresh commented on examples/image-test-workflow/versions/0.0.1/workflowTemplate.yaml
> +          argo-hub-template/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/image-test-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/image-test-workflow/assets/icon.svg"

2022-08-03 22:08 UTC, eti-codefresh commented on examples/image-test-workflow/versions/0.0.1/workflowTemplate.yaml
> +          argo-hub-template/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/image-test-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/image-test-workflow/assets/icon.svg"

2022-09-01 21:40 UTC, lrochette approved these changes

2022-09-01 21:48 UTC, lrochette commented
Too much junk. Closing and deleting branch

2022-09-01 21:48 UTC, closed without merging