Workflowtemp1 (#396)
codefresh-io/argo-hub pull request #399
Opened 2022-07-29 22:01 UTC by matthewchungcodefresh

* Workflow-template-jirascan

* Update README.md

* Update workflowTemplate.yaml

2022-07-30 00:55 UTC, lrochette requested changes

2022-07-30 00:55 UTC, lrochette commented on examples/jira-scan-workflow/versions/0.0.1/docs/jira-sonar-template.md
> +* IMAGE_SHA (required) - The image sha that was imported into Codefresh to enrich
this should not be a parameter, it is returned by image-report-info
one does not know the SHA image at the start of a build

2022-07-30 00:55 UTC, lrochette commented on examples/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +          - name: value-to-promote
it's strange to mix upper and lower case for parameters, stick to 1 format

2022-07-30 00:55 UTC, lrochette commented on examples/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +        parameters:
it's a bunch load of parameters

2022-07-30 00:55 UTC, lrochette commented on examples/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +                  from: "{{tasks.clone-step-repo.outputs.artifacts.REPO}}"
this should be "tasks.clone-step-repo.outputs.artifacts.repo" in lower case as defined in the block

`      outputs:
        artifacts:
          - name: repo
            path: /tmp/repo
`
in the clone template
How were you able to make it run?

2022-08-03 22:06 UTC, eti-codefresh requested changes

2022-08-03 22:06 UTC, eti-codefresh commented on examples/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +    argo-hub/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/jira-scan-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/jira-scan-workflow/assets/icon.svg"

2022-08-03 22:06 UTC, eti-codefresh commented on examples/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +          argo-hub-template/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/jira-scan-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/jira-scan-workflow/assets/icon.svg"

2022-08-03 22:06 UTC, eti-codefresh commented on examples/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +          argo-hub-template/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/jira-scan-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/jira-scan-workflow/assets/icon.svg"

2022-08-03 22:06 UTC, eti-codefresh commented on examples/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +          argo-hub-template/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/jira-scan-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/jira-scan-workflow/assets/icon.svg"

2022-08-03 22:06 UTC, eti-codefresh commented on examples/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +          argo-hub-template/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/jira-scan-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/jira-scan-workflow/assets/icon.svg"

2022-08-03 22:06 UTC, eti-codefresh commented on examples/jira-scan-workflow/versions/0.0.1/workflowTemplate.yaml
> +          argo-hub-template/icon_url: "https://github.com/codefresh-io/argo-hub/blob/main/examples/jira-scan-workflow/assets/icon.svg"
need to be change to this "https://cdn.jsdelivr.net/gh/codefresh-io/argo-hub@main/examples/jira-scan-workflow/assets/icon.svg"

2022-08-12 23:32 UTC, lrochette approved these changes

2022-08-14 12:30 UTC, eti-codefresh approved these changes

2022-08-16 16:25 UTC, merged