Add Port (getport.io) workflow templates
codefresh-io/argo-hub pull request #471
Opened 2022-12-21 17:26 UTC by MPTG94

Hi,

I'm a solution architect at [Port](https://getport.io), some of our clients are using codefresh and we wanted to give them an easy way to interact with their developer portal as part of their Codefresh CI process.

I opened a PR with a WorkflowTemplate that can be used as part of the Codefresh CI process to interact with Port.

I'll be happy to make additional changes to make sure the template is up to your standards and can be added to your Argo-hub.

2023-01-17 17:27 UTC, eti-codefresh requested changes

2023-01-23 15:52 UTC, MPTG94 commented on workflows/port/versions/1.0.0/docs/entity-upsert.md
> +- `ENTITY_TITLE` - Title of the new (or existing) entity;
@eti-codefresh added explanation about default value for each field

2023-01-23 15:52 UTC, MPTG94 commented on workflows/port/versions/1.0.0/workflowTemplate.yaml
> +        image: quay.io/codefreshplugins/argo-hub-workflows-port-versions-1.0.0-images-codefresh-port-entity:main
@eti-codefresh updated

2023-01-23 15:52 UTC, MPTG94 commented on workflows/port/versions/1.0.0/workflowTemplate.yaml
> +        image: quay.io/codefreshplugins/argo-hub-workflows-port-versions-1.0.0-images-codefresh-port-entity:main
@eti-codefresh updated

2023-02-02 11:48 UTC, eti-codefresh approved these changes

2023-02-02 11:48 UTC, eti-codefresh reviewed
@MPTG94 approved

2023-02-08 13:40 UTC, MPTG94 commented
Hey @eti-codefresh, I added version 1.1.0 to this PR because it is also ready.

You can go ahead and merge the PR if that's ok on your side

2023-02-27 11:44 UTC, MPTG94 commented
@eti-codefresh @francisco-codefresh checking if there is any update, I do not have permissions to merge this

2023-03-30 17:05 UTC, merged